# Generated by Django 4.2.7 on 2023-12-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.CharField(max_length=120)),
                ('name', models.TextField()),
                ('email', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('contact', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SignUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.CharField(max_length=120)),
                ('username', models.TextField()),
                ('password', models.CharField(max_length=120)),
            ],
        ),
    ]
