name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull docker image
        run: sudo docker pull littlebrackets/cicd-pipeline:v1.0.1 
      - name: Delete old docker image
        run: sudo docker rm -f cicd-pipeline-container || true
      - name: Run docker container
        run: sudo docker run -d -p 8000:8000 --name cicd-pipeline-container littlebrackets/cicd-pipeline