name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push Docker image
        run: |
          docker build -t educatu-server:v1.0.1 .
          docker tag educatu-server:v1.0.1 docker.io/littlebrackets/educatu-server:v1.0.1
          docker push docker.io/littlebrackets/educatu-server:v1.0.1        