name: Docker Image CI

on:
  push:
    branches: [ "main" ] 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub      
      run:  docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: build the docker image  
      run: docker build -t littlebrackets/cicd-pipeline .
    - name: push to dockerhub repo
      run: docker push littlebrackets/cicd-pipeline:latest 
