# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ] 

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Login Dockerhub      
#       run:  docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
#     - name: build the docker image  
#       run: docker build -t littlebrackets/cicd-pipeline:latest .
#     - name: push to dockerhub repo
#       run: docker push littlebrackets/cicd-pipeline:latest 




name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push Docker image
        run: |
          docker build -t cicd-pipeline:latest .
          docker tag cicd-pipeline:latest docker.io/littlebrackets/cicd-pipeline:latest
          docker push docker.io/littlebrackets/cicd-pipeline:latest
        env:
          DOCKER_CLI_ASK_PASS: 0
